### ISSUE TITLE
error in execution

### ISSUE THREAD

**Issue by adnankhawaja** [cbellei/word2veclite#2]
Traceback (most recent call last):
  File "w2veclite.py", line 4, in <module>
    W1, W2, loss_vs_epoch = cbow.run()
  File "D:\aconda\lib\site-packages\word2veclite\word2veclite.py", line 113, in run
    W1, W2, loss = self.method(context, center, W1, W2, loss)
  File "D:\aconda\lib\site-packages\word2veclite\word2veclite.py", line 47, in cbow
    h = np.dot(W1.T, x)
ValueError: shapes (2,7) and (2,7) not aligned: 7 (dim 1) != 2 (dim 0)

**Comment by cbellei** [comment]
Hi @adnankhawaja,
Make sure you are using the right versions as in the requirements.txt file. In particular the code uses numpy v1.13.3. Let me know if you still have problems!

**Comment by cbellei** [comment]
Closing this issue as the latest changes should address using more recent versions of numpy.
